export const GET_ALL_SWEETS_REQUEST = "GET_ALL_SWEETS_REQUEST";
export const GET_ALL_SWEETS_SUCCESS = "GET_ALL_SWEETS_SUCCESS";
export const GET_ALL_SWEETS_FAILURE = "GET_ALL_SWEETS_FAILURE";

export const SEARCH_SWEETS_REQUEST = "SEARCH_SWEETS_REQUEST";
export const SEARCH_SWEETS_SUCCESS = "SEARCH_SWEETS_SUCCESS";
export const SEARCH_SWEETS_FAILURE = "SEARCH_SWEETS_FAILURE";

export const PURCHASE_SWEET_REQUEST = "PURCHASE_SWEET_REQUEST";
export const PURCHASE_SWEET_SUCCESS = "PURCHASE_SWEET_SUCCESS";
export const PURCHASE_SWEET_FAILURE = "PURCHASE_SWEET_FAILURE";

export const ADD_SWEET_REQUEST = "ADD_SWEET_REQUEST";
export const ADD_SWEET_SUCCESS = "ADD_SWEET_SUCCESS";
export const ADD_SWEET_FAILURE = "ADD_SWEET_FAILURE";

export const UPDATE_SWEET_REQUEST = "UPDATE_SWEET_REQUEST";
export const UPDATE_SWEET_SUCCESS = "UPDATE_SWEET_SUCCESS";
export const UPDATE_SWEET_FAILURE = "UPDATE_SWEET_FAILURE";

export const DELETE_SWEET_REQUEST = "DELETE_SWEET_REQUEST";
export const DELETE_SWEET_SUCCESS = "DELETE_SWEET_SUCCESS";
export const DELETE_SWEET_FAILURE = "DELETE_SWEET_FAILURE";

export const RESTOCK_SWEET_REQUEST = "RESTOCK_SWEET_REQUEST";
export const RESTOCK_SWEET_SUCCESS = "RESTOCK_SWEET_SUCCESS";
export const RESTOCK_SWEET_FAILURE = "RESTOCK_SWEET_FAILURE";