name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'Dockerfile'
      - '.github/**'

jobs:
  deploy:
    name: Build & Deploy Docker Image to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests --file pom.xml

      - name: Set up Google Cloud CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Set GCP project and region
        run: |
          gcloud config set project sweet-shop10
          gcloud config set run/region asia-south1

      - name: Build Docker Image
        run: docker build --platform=linux/amd64 -t asia-south1-docker.pkg.dev/sweet-shop10/sweet-shop-repo/sweet-shop-backend .

      - name: Push Docker Image to Artifact Registry
        run: docker push asia-south1-docker.pkg.dev/sweet-shop10/sweet-shop-repo/sweet-shop-backend

      - name: Deploy to Cloud Run
        run: gcloud run deploy sweet-shop-backend --image asia-south1-docker.pkg.dev/sweet-shop10/sweet-shop-repo/sweet-shop-backend:latest --platform managed --region asia-south1 --allow-unauthenticated --set-env-vars "SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE}},DB_URL=${{ secrets.DB_URL}},DB_USERNAME=${{ secrets.DB_USERNAME}},DB_PASSWORD=${{ secrets.DB_PASSWORD}},FRONTEND_URL=${{ secrets.FRONTEND_URL}},SERVER_PORT=${{ secrets.SERVER_PORT}},JWT_SECRET=${{ secrets.JWT_SECRET}},JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}"